	<div class="row">
				<div class="large-12 columns ebslgfooter">
					<h6 class="subheader"> 
	  					European Business School Librarians&rsquo; Group (EBSLG) &copy; <!--#config timefmt="%Y" --><!--#echo var="DATE_GMT" --> &nbsp;|&nbsp;<a href="/cookies/">Cookies</a>&nbsp;|&nbsp;<a href="/sitemap/">Site Map</a>&nbsp;|&nbsp;
	  					Page updated: <!--#config timefmt="%d %B %Y" --><!--#echo var="LAST_MODIFIED" --></a>
					</h6>
				</div>
	</div>
