<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script
    async
    src="https://www.googletagmanager.com/gtag/js?id=G-6G0HGDHXXQ"
  ></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag("js", new Date());

    gtag("config", "G-6G0HGDHXXQ");
  </script>
  <!-- End Global site tag (gtag.js) - Google Analytics -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>
    EBSLG: European Business School Librarians' Group (EBSLG): <!--#echo
    var="mytitle" -->
  </title>
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
  <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
  <link
    rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Bitter"
  />
  <link rel="stylesheet" href="/css/foundation.css" />
  <link rel="stylesheet" href="/css/app.css" />
  <link rel="stylesheet" href="/stylesheets/general_foundicons.css" />
  <link rel="stylesheet" href="/stylesheets/general_enclosed_foundicons.css" />
  <script src="/js/vendor/custom.modernizr.js"></script>
</head>
