<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>EBSLG: European Business Schools Librarians' Group (EBSLG): <!--#echo var="mytitle" --></title>
  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
  <link rel="apple-touch-icon" href="/apple-touch-icon.png"/>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:700" integrity="sha384-ts1NdUqeCEWKOjG8xMqPi3e2ziq8cgl7gR2k+yoTn1N9rtLRx3h+yYmvkwYFkR8n" crossorigin="anonymous">
  <link rel="stylesheet" href="/css/foundation.css">
  <link rel="stylesheet" href="/css/app.css">
  <link rel="stylesheet" href="/stylesheets/general_foundicons.css">  
  <link rel="stylesheet" href="/stylesheets/general_enclosed_foundicons.css">
  <script src="/js/vendor/custom.modernizr.js"></script>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1010997-2', 'auto');
  ga('send', 'pageview');

  </script>
</head>