<div class="row show-for-small">
	<div class="small-12 columns small-logo">
		<img src="/img/banner-globe-europe-small.png" alt="" />
	</div>
</div>

<div class="row hide-for-print hide-for-small">
		<div class="large-12 columns">
			<div> 
				<ul class="carousel-orbit" data-orbit data-options="pause_on_hover:false;animation:'fade';timer_speed:5000;">
   					<li id="LibCntntl"></li>
  					<li id="LibNorth"></li>
  					<li id="LibAnglo"></li>
				</ul>
			</div>
			<hr />
		</div>
</div>