<div class="large-3 columns">
  <div class="panel inverted">
    <h4>Quick Links</h4>

    <div class="row">
      <div class="large-2 small-1 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li>
            <a href="https://sites.google.com/site/ebslgmembers/"
              ><i class="gen-enclosed foundicon-people"></i
            ></a>
          </li>
        </ul>
      </div>
      <div class="large-10 small-11 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li>
            <a href="https://sites.google.com/site/ebslgmembers/"
              >Members&rsquo; site</a
            >
          </li>
        </ul>
      </div>
    </div>
    <!-- /row -->

    <div class="row">
      <div class="large-2 small-1 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li>
            <a href="https://basecamp.com/2973848/"
              ><i class="gen-enclosed foundicon-people"></i
            ></a>
          </li>
        </ul>
      </div>
      <div class="large-10 small-11 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li><a href="https://basecamp.com/2973848/">Basecamp</a></li>
        </ul>
      </div>
    </div>
    <!-- /row -->

    <div class="row">
      <div class="large-2 small-1 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li>
            <a href="https://bit.ly/ebslg-map"
              ><i class="gen-enclosed foundicon-location"></i
            ></a>
          </li>
        </ul>
      </div>
      <div class="large-10 small-11 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li><a href="https://bit.ly/ebslg-map">Member Location Map</a></li>
        </ul>
      </div>
    </div>
    <!-- /row -->

    <div class="row">
      <div class="large-2 small-1 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li>
            <a href="https://www.abld.org"
              ><i class="gen-enclosed foundicon-globe"></i
            ></a>
          </li>
        </ul>
      </div>
      <div class="large-10 small-11 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li>
            <a href="https://www.abld.org"
              >ABLD - Academic Business Library Directors</a
            >
          </li>
        </ul>
      </div>
    </div>
    <!-- /row -->

    <div class="row">
      <div class="large-2 small-1 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li>
            <a href="https://www.isb.edu/en/apbslg.html"
              ><i class="gen-enclosed foundicon-globe"></i
            ></a>
          </li>
        </ul>
      </div>
      <div class="large-10 small-11 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li>
            <a href="https://www.isb.edu/en/apbslg.html"
              >APBSLG – Asia-Pacific Business School Librarians’ Group</a
            >
          </li>
        </ul>
      </div>
    </div>
    <!-- /row -->
    <div class="row">
      <div class="large-2 small-1 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li>
            <a href="https://www.isb.edu/en/apbslg.html"
              ><i class="gen-enclosed foundicon-globe"></i
            ></a>
          </li>
        </ul>
      </div>
      <div class="large-10 small-11 columns">
        <ul class="side-nav" style="padding-top: 0; margin-top: 0">
          <li>
            <a href="https://cladea.org/en/home/"
              >CLADEA – Latin American Council of Management Schools</a
            >
          </li>
        </ul>
      </div>
    </div>
    <!-- /row -->
  </div>
  <!-- /panel inverted -->
</div>
<!-- /large-3 -->
