<div class="large-3 columns">
	<div class="panel inverted">
			<h4>Quick Links</h4>
				
				<div class="row">
  					<div class="large-2 small-1 columns">
  					  	<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="http://sites.google.com/site/ebslgmembers"><i class="gen-enclosed foundicon-people"></i></a></li>
						</ul>
  					</div>					 					
  					<div class="large-10 small-11 columns">
  						<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="http://sites.google.com/site/ebslgmembers">Members&rsquo; site</a></li>
						</ul>
  					</div>
				</div><!-- /row -->
				
			<div class="row">
  					<div class="large-2 small-1 columns">
  					  	<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="https://basecamp.com/2973848/"><i class="gen-enclosed foundicon-people"></i></a></li>
						</ul>
  					</div>					 					
  					<div class="large-10 small-11 columns">
  						<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="https://basecamp.com/2973848/">Basecamp</a></li>
						</ul>
  					</div>
				</div><!-- /row -->
				
				<div class="row">
  					<div class="large-2 small-1 columns">
  					  	<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="https://sites.google.com/a/wfu.edu/abld/home/membership"><i class="gen-enclosed foundicon-globe"></i></a></li>
						</ul>
  					</div>					 					
  					<div class="large-10 small-11 columns">
  						<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="https://sites.google.com/view/abld/home">ABLD - Academic Business Library Directors</a></li>
						</ul>
  					</div>
				</div><!-- /row -->
				
				<div class="row">
  					<div class="large-2 small-1 columns">
  					  	<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="http://www.isb.edu/apbslg/"><i class="gen-enclosed foundicon-globe"></i></a></li>
						</ul>
  					</div>					 					
  					<div class="large-10 small-11 columns">
  						<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="http://www.isb.edu/apbslg/">APBSLG – Asia-Pacific Business School Librarians’ Group</a></li>
						</ul>
  					</div>
				</div><!-- /row -->
				<div class="row">
  					<div class="large-2 small-1 columns">
  					  	<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="http://www.isb.edu/apbslg/"><i class="gen-enclosed foundicon-globe"></i></a></li>
						</ul>
  					</div>					 					
  					<div class="large-10 small-11 columns">
  						<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="https://www.cladea.org/en/">CLADEA – Latin American Council of Management Schools</a></li>
						</ul>
  					</div>
				</div><!-- /row -->

												
	</div><!-- /panel inverted -->
	
		<div class="panel inverted meetings">
				<div class="row">
				<h4>Regional News</h4>
				<hr />
				<h5>UK and Ireland Group Meeting <!--<a href="https://basecamp.com/2973848/projects/12824425"><img width="16" height="16" src="../img/basecamp.png" alt="Basecamp" /></a>--></h5>
  				<p>The most recent UK and Ireland Group meeting was held online on 22 January 2021.</p>
				</div><!-- /row -->
				<hr />
				<div class="row">
  				<h5>Continental Group Meeting <!--<a href="https://basecamp.com/2973848/projects/12824668"><img width="16" height="16" src="../img/basecamp.png" alt="Basecamp" /></a>--></h5>
				<p>The most recent Continental group meeting was held at <a href="https://www.vlerick.com/en/ebslg-conference">Vlerick Business School</a> between 9th and 11th October 2019.</p>  				</div><!-- /row -->
				<hr />
				
				<div class="row">
  				<h5>Northern Group Meeting</h5>
  				<p>The most recent Northern Group meeting was held online on 18 March 2021.</p>
				</div><!-- /row -->
	
										
	</div><!-- /panel inverted -->
	
</div><!-- /large-3 -->
