<div class="large-3 columns">
	<div class="panel inverted">
			<h4>Quick Links</h4>
				
				<div class="row">
  					<div class="large-2 small-1 columns">
  					  	<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="http://sites.google.com/site/ebslgmembers"><i class="gen-enclosed foundicon-people"></i></a></li>
						</ul>
  					</div>					 					
  					<div class="large-10 small-11 columns">
  						<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="http://sites.google.com/site/ebslgmembers">Members&rsquo; site</a></li>
						</ul>
  					</div>
				</div><!-- /row -->
				
				<div class="row">
  					<div class="large-2 small-1 columns">
  					  	<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="https://sites.google.com/a/wfu.edu/abld/home/membership"><i class="gen-enclosed foundicon-globe"></i></a></li>
						</ul>
  					</div>					 					
  					<div class="large-10 small-11 columns">
  						<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="https://sites.google.com/a/wfu.edu/abld/home/membership">ABLD - Academic Business Library Directors</a></li>
						</ul>
  					</div>
				</div><!-- /row -->
				
				<div class="row">
  					<div class="large-2 small-1 columns">
  					  	<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="http://www.isb.edu/apbslg/"><i class="gen-enclosed foundicon-globe"></i></a></li>
						</ul>
  					</div>					 					
  					<div class="large-10 small-11 columns">
  						<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="http://www.isb.edu/apbslg/">APBSLG – Asia-Pacific Business School Librarians’ Group</a></li>
						</ul>
  					</div>
				</div><!-- /row -->
				<div class="row">
  					<div class="large-2 small-1 columns">
  					  	<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="http://www.isb.edu/apbslg/"><i class="gen-enclosed foundicon-globe"></i></a></li>
						</ul>
  					</div>					 					
  					<div class="large-10 small-11 columns">
  						<ul class="side-nav" style="padding-top:0; margin-top:0;">
							<li><a href="http://cladea.org/index.php?option=com_content&amp;view=article&amp;id=228&amp;Itemid=326&amp;lang=es">CLADEA – Latin American Council of Management Schools</a></li>
						</ul>
  					</div>
				</div><!-- /row -->

												
	</div><!-- /panel inverted -->
	
		<div class="panel inverted meetings">
				<div class="row">
				<h4>Regional News</h4>
				<hr />
			<!-- Goodbye Roogly -->
  					<p>The EBSLG wishes to acknowledge the very deep sadness of all the members at the loss of our much esteemed and respected colleague and friend, Jane Marshall, Academic Engagement Librarian at the University of Manchester, who passed away tragically on Friday 25th, 2016.</p>
<!-- /Goodbye Roogly -->

							</div><!-- /row -->
	
										
	</div><!-- /panel inverted -->
	
</div><!-- /large-3 -->
