<div class="row orbit-heading">
		<div class="large-12 columns">
			<h3>European Business Schools Librarians&rsquo; Group</h3>
		</div>
</div>

<div class="row">
	<div class="large-12 columns">
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <!--<h1 class="hide-for-small show-for-print"><a href="#">EBSLG: European Business Schools Librarians&rsquo; Group</a></h1>
      <h1 class="hide-for-large hide-for-medium hide-for-print"><a href="#">EBSLG</a></h1>-->
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->

    
    <!-- Left Nav Section -->
    <ul class="left">
    <li id="top-bar-home"><a href="/">Home</a></li>
    <li class="divider"></li>
     <li id="top-bar-about" class="has-dropdown">
        <a href="/about">About Us</a>
        <ul class="dropdown">
      		<li id="top-bar-about-history"><a href="/about/history">History</a></li>
      		<li id="top-bar-about-purpose"><a href="/about/purpose">Purpose</a></li>
      		<li id="top-bar-about-council"><a href="/about/council">Council</a></li>
      		<li id="top-bar-about-constitution"><a href="/about/constitution">Constitution</a></li>
      		<li id="top-bar-about-membership"><a href="/about/membership">Membership</a></li>
        </ul>
      </li>
      <!--<li class="divider"></li>
      <li id="top-bar-news"><a href="/news">News</a></li>-->
      <!--<li class="divider"></li>
      <li id="top-bar-events"><a href="/events">Events</a></li>-->
      <li class="divider"></li>
      <li id="top-bar-members"><a href="/members">Directory of members</a></li>
      <li class="divider"></li>
      <li id="top-bar-libraries"><a href="/libraries">Directory of libraries</a></li>
      <!--<li class="divider"></li>
      <li id="top-bar-presentations"><a href="/presentations">Presentations</a></li>-->
      <li class="divider"></li>
      <li id="top-bar-contact"><a href="/contact">Contact us</a></li>
      <li class="divider"></li>
      <!--<li class="hide-for-small" style="background:#0a8a36; width:16em;"><a href="#" style="background:#0a8a36;">&nbsp;</a></li>-->
    </ul>
    
  </section>
</nav>
	</div><!-- End .large-12 columns -->
</div><!-- End .row -->